# Configuração do Netlify
[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# opcional: cabeçalhos básicos
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
